<?php

namespace Database\Seeders;

use App\Models\PageSection;
use Illuminate\Database\Seeder;

class PageSectionSeeder extends Seeder
{
    public function run(): void
    {
        // -- HOME --
        PageSection::create(['page'=>'home','section_key'=>'hero','title'=>'Sewa Bus Pariwisata Premium','subtitle'=>'Satu armada,<br/> <span class="purple">tak terbatas</span><br/>petualangan.','description'=>'PHD Trans menghadirkan armada bus pariwisata terbaik untuk perjalanan Anda. Nyaman, aman, dan harga transparan.','media_type'=>'none','metadata'=>[['key'=>'armada_count','value'=>'50+','label'=>'Armada Tersedia'],['key'=>'pelanggan_count','value'=>'1K+','label'=>'Pelanggan Puas'],['key'=>'tahun_count','value'=>'10+','label'=>'Tahun Pengalaman']],'sort_order'=>1,'is_active'=>true]);
        PageSection::create(['page'=>'home','section_key'=>'closing_cta','title'=>'Siap memulai<br/>perjalanan<br/>Anda?','subtitle'=>'Booking · 2026','description'=>'Jelajahi armada kami dan pilih bus yang sesuai dengan kebutuhan perjalanan Anda. Tim kami siap membantu.','media_type'=>'none','sort_order'=>2,'is_active'=>true]);

        // -- ABOUT --
        PageSection::create(['page'=>'home','section_key'=>'media_feature','title'=>'Lihat <span class="purple">Armada</span> Kami','subtitle'=>'Galeri','description'=>'Jelajahi koleksi armada Big Bus dan Medium Bus kami. Semua unit dalam kondisi prima dan siap menemani perjalanan Anda.','media_type'=>'gallery','sort_order'=>3,'is_active'=>true]);

        PageSection::create(['page'=>'about','section_key'=>'hero','title'=>'Satu tim,<br/> <span class="purple">satu visi</span>,<br/> melayani Anda.','subtitle'=>'Perusahaan · est. 2015','description'=>'PHD Trans adalah perusahaan penyewaan bus pariwisata yang berdiri sejak 2015. Berawal dari 3 unit bus, kini kami memiliki lebih dari 50 armada yang siap melayani perjalanan Anda.','media_type'=>'none','metadata'=>[['key'=>'tahun_berdiri','value'=>'2015','label'=>'Tahun berdiri'],['key'=>'armada_count','value'=>'50+','label'=>'Armada'],['key'=>'karyawan_count','value'=>'25','label'=>'Karyawan']],'sort_order'=>1,'is_active'=>true]);
        PageSection::create(['page'=>'about','section_key'=>'about_content','title'=>'Perjalanan<br/>PHD <span class="purple">Trans</span>','subtitle'=>'Cerita Kami','description'=>'<p>Berawal dari kecintaan terhadap dunia transportasi, PHD Trans hadir untuk memberikan solusi perjalanan yang nyaman, aman, dan terjangkau bagi masyarakat Indonesia.</p><p>Selama 15 tahun, kami telah melayani ribuan pelanggan — mulai dari study tour sekolah, corporate gathering, family trip, hingga transportasi acara besar.</p>','media_type'=>'none','sort_order'=>2,'is_active'=>true]);
        PageSection::create(['page'=>'about','section_key'=>'values','title'=>'Nilai <span class="purple">Kami</span>','subtitle'=>'Tiga pilar yang menjaga kualitas','metadata'=>[['key'=>'keamanan','value'=>'Keamanan','icon'=>'🔒','desc'=>'Setiap bus menjalani pemeriksaan rutin dan perawatan berkala.'],['key'=>'kenyamanan','value'=>'Kenyamanan','icon'=>'💺','desc'=>'Armada dilengkapi AC, reclining seat, hiburan, dan rest area.'],['key'=>'profesionalisme','value'=>'Profesionalisme','icon'=>'👔','desc'=>'Sopir berpengalaman dan ramah, serta tim CS 24/7.']],'sort_order'=>3,'is_active'=>true]);
        PageSection::create(['page'=>'about','section_key'=>'stats','metadata'=>[['value'=>'15','label'=>'Tahun Pengalaman','icon'=>'🏆'],['value'=>'50+','label'=>'Armada Bus','icon'=>'🚌'],['value'=>'1K+','label'=>'Pelanggan Puas','icon'=>'😊'],['value'=>'25','label'=>'Tim Profesional','icon'=>'👥']],'sort_order'=>4,'is_active'=>true]);
        PageSection::create(['page'=>'about','section_key'=>'closing_cta','title'=>'Siap memulai<br/>perjalanan<br/>bersama kami?','subtitle'=>'Bersama PHD Trans','description'=>'Hubungi kami untuk konsultasi dan pemesanan. Tim kami siap membantu Anda memilih armada yang tepat.','media_type'=>'none','sort_order'=>5,'is_active'=>true]);

        // -- SERVICES --
        PageSection::create(['page'=>'services','section_key'=>'hero','title'=>'Dua pilihan<br/> <span class="purple">armada,</span> satu<br/> standar kualitas.','subtitle'=>'Dua tipe · Satu layanan','description'=>'Kami menawarkan Big Bus dan Medium Bus dengan harga yang transparan.','media_type'=>'none','metadata'=>[['key'=>'armada_tipe','value'=>'2','label'=>'Tipe Armada'],['key'=>'unit_tersedia','value'=>'50+','label'=>'Unit Tersedia']],'sort_order'=>1,'is_active'=>true]);
        PageSection::create(['page'=>'services','section_key'=>'process','title'=>'Cara <span class="purple">Sewa</span>','subtitle'=>'Proses penyewaan bus di PHD Trans mudah dan cepat. Hanya 4 langkah sederhana.','metadata'=>[['step'=>'01','value'=>'Pilih Armada','desc'=>'Jelajahi koleksi armada Big Bus dan Medium Bus kami.'],['step'=>'02','value'=>'Pesan & Bayar','desc'=>'Isi form booking dengan tanggal, tujuan, dan detail perjalanan.'],['step'=>'03','value'=>'Verifikasi','desc'=>'Tim admin kami akan memverifikasi pembayaran dan booking Anda.'],['step'=>'04','value'=>'Nikmati Perjalanan','desc'=>'Sopir akan tiba sesuai jadwal. Nikmati perjalanan Anda.']],'sort_order'=>2,'is_active'=>true]);
        PageSection::create(['page'=>'services','section_key'=>'faq','title'=>'Pertanyaan <span class="purple">Umum</span>','subtitle'=>'Jawaban cepat untuk pertanyaan yang sering diajukan.','metadata'=>[['q'=>'Apa saja yang termasuk harga sewa?','a'=>'Harga sudah termasuk sopir, bahan bakar, dan fasilitas standar bus.'],['q'=>'Berapa deposit yang harus dibayar?','a'=>'Minimal DP 50% dari total harga. Pelunasan dapat dilakukan H-1.'],['q'=>'Apakah bisa booking untuk perjalanan multi-hari?','a'=>'Tentu. Kami melayani perjalanan multi-hari dengan paket khusus.'],['q'=>'Apakah sopir sudah termasuk?','a'=>'Ya, semua paket sudah termasuk sopir profesional dan ramah.'],['q'=>'Bagaimana jika booking dibatalkan?','a'=>'Pembatalan H-7: DP dikembalikan 50%. H-3: tidak dapat refund.']],'sort_order'=>3,'is_active'=>true]);
        PageSection::create(['page'=>'services','section_key'=>'closing_cta','title'=>'Ada pertanyaan<br/>lain? Tanya<br/>kami saja.','subtitle'=>'Booking · 2026','description'=>'Tim kami siap membantu Anda memilih armada yang tepat dan menjawab semua pertanyaan Anda.','media_type'=>'none','sort_order'=>4,'is_active'=>true]);

        // -- CONTACT --
        PageSection::create(['page'=>'contact','section_key'=>'hero','title'=>'Kirim pesan,<br/> <span class="purple">dapatkan</span><br/> jawaban.','subtitle'=>'Respon dalam 24 jam kerja','description'=>'Setiap pertanyaan dibaca dan dijawab oleh tim customer service kami.','media_type'=>'none','metadata'=>[['key'=>'respon_time','value'=>'24 jam','label'=>'target respon'],['key'=>'jam_kerja','value'=>'Senin—Sabtu','label'=>'08:00–20:00']],'sort_order'=>1,'is_active'=>true]);
        PageSection::create(['page'=>'contact','section_key'=>'channels','title'=>'Hubungi <span class="purple">Kami</span>','subtitle'=>'Tiga cara mudah untuk terhubung dengan tim PHD Trans.','metadata'=>[['channel'=>'wa','icon'=>'💬','value'=>'WhatsApp','desc'=>'Respon cepat via WhatsApp.','label'=>'CS · Respon < 24 jam'],['channel'=>'email','icon'=>'📧','value'=>'Email','desc'=>'Kirim email untuk pertanyaan detail.','label'=>'Admin · Respon 1×24 jam']],'sort_order'=>2,'is_active'=>true]);
        PageSection::create(['page'=>'contact','section_key'=>'contact_info','title'=>'📍 Kantor Pusat','description'=>'Senin — Sabtu: 08:00 – 20:00<br/>Minggu & Hari Libur: 09:00 – 17:00','sort_order'=>3,'is_active'=>true]);
        PageSection::create(['page'=>'contact','section_key'=>'closing_cta','title'=>'Kirim pesan,<br/>kami akan<br/>membalas.','subtitle'=>'Siap memesan?','description'=>'Tidak suka form? Hubungi kami langsung via WhatsApp atau email.','media_type'=>'none','sort_order'=>4,'is_active'=>true]);
    }
}
